In [1]:
! ls

RNN_100_subb.ipynb		      wordList-200.npy
train_clean_subb_withuser_sorted.csv  wordVectors-200.npy


In [2]:
import numpy as np
import pandas as pd

csv = 'train_clean_subb_withuser_sorted.csv'
df = pd.read_csv(csv)
df.head()

id                                               text  target
0  91976  user user user think it is safe bet that donal...     1.0
1  15435                             user got your ass lmao     1.0
2  63384  user dick durbin figures if he lies often enou...     1.0
3  88928                                          user sexy     1.0
4  21615  user user think he is racist out of touch with...     1.0

In [3]:
!ls

RNN_100_subb.ipynb		      wordList-200.npy
train_clean_subb_withuser_sorted.csv  wordVectors-200.npy


In [4]:
wordsList = np.load('wordList-200.npy')
print('Loaded the word list!')
wordsList = wordsList.tolist() #Originally loaded as numpy array
wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
wordVectors = np.load('wordVectors-200.npy')
print ('Loaded the word vectors!')

Loaded the word list!
Loaded the word vectors!


In [10]:
import tensorflow as tf
maxSeqLength = 10 #Maximum length of sentence
numDimensions = 200 #Dimensions for each word vector
firstSentence = np.zeros((maxSeqLength), dtype='int32')
firstSentence[0] = wordsList.index("i")
firstSentence[1] = wordsList.index("thought")
firstSentence[2] = wordsList.index("the")
firstSentence[3] = wordsList.index("movie")
firstSentence[4] = wordsList.index("was")
firstSentence[5] = wordsList.index("incredible")
firstSentence[6] = wordsList.index("and")
firstSentence[7] = wordsList.index("inspiring")
#firstSentence[8] and firstSentence[9] are going to be 0
print(firstSentence.shape)
print(firstSentence) #Shows the row index for each word

(10,)
[   41   804     0  1005    15  7446     5 13767     0     0]


In [11]:
#from os import listdir
#from os.path import isfile, join
#positiveFiles = ['positiveReviews/' + f for f in listdir('positiveReviews/') if isfile(join('positiveReviews/', f))]
#negativeFiles = ['negativeReviews/' + f for f in listdir('negativeReviews/') if isfile(join('negativeReviews/', f))]
numWords = []
k = df.text
#k = np.array(k)

for i in range(len(k)) :
  line = str(k[i])
  counter = len(line.split())
  numWords.append(counter)
  
  

#for pf in positiveFiles:
#    with open(pf, "r", encoding='utf-8') as f:
#        line=f.readline()
#        counter = len(line.split())
#        numWords.append(counter)       
#print('Positive files finished')

#for nf in negativeFiles:
#    with open(nf, "r", encoding='utf-8') as f:
#        line=f.readline()
#        counter = len(line.split())
#        numWords.append(counter)  
#print('Negative files finished')

numFiles = len(numWords)
print('The total number of files is', numFiles)
print('The total number of words in the files is', sum(numWords))
print('The average number of words in the files is', sum(numWords)/len(numWords))



The total number of files is 4400
The total number of words in the files is 98451
The average number of words in the files is 22.375227272727273


In [12]:
with tf.Session() as sess:
    print(tf.nn.embedding_lookup(wordVectors,firstSentence).eval().shape)

(10, 200)


In [13]:
k = df.text

In [14]:
maxSeqLength = 65

In [15]:
# Removes punctuation, parentheses, question marks, etc., and leaves only alphanumeric characters
import re
strip_special_chars = re.compile("[^A-Za-z0-9 ]+")

def cleanSentences(string):
    string = string.lower().replace("<br />", " ")
    return re.sub(strip_special_chars, "", string.lower())

In [16]:
ids = np.zeros((numFiles, maxSeqLength), dtype='int32')
fileCounter = 0

for i in range(len(k)) :
  indexCounter = 0
  line = str(k[i])
  cleanedLine = cleanSentences(line)
  split = cleanedLine.split()
  for word in split:
    try :
      ids[fileCounter][indexCounter] = wordsList.index(word)
    except ValueError:
      ids[fileCounter][indexCounter] = 399999
      
    indexCounter = indexCounter + 1  
    if indexCounter >= maxSeqLength:
      break
  fileCounter = fileCounter + 1   
      
      
      

# for pf in positiveFiles:
#    with open(pf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 

# for nf in negativeFiles:
#    with open(nf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 
# #Pass into embedding function and see if it evaluates. 

# np.save('idsMatrix', ids)

In [17]:
df.text[3400]

'user user no real american would watch this crap'

In [18]:
ids[3400]

array([ 4832,  4832,    84,   567,   140,    54,  1716,    37, 35404,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0], dtype=int32)

In [19]:
np.save('idsMatrix', ids)

In [0]:
ids = np.load('idsMatrix.npy')

In [20]:
df.head()

id                                               text  target
0  91976  user user user think it is safe bet that donal...     1.0
1  15435                             user got your ass lmao     1.0
2  63384  user dick durbin figures if he lies often enou...     1.0
3  88928                                          user sexy     1.0
4  21615  user user think he is racist out of touch with...     1.0

In [21]:
labels1 = []
p = df.target
for i in range(len(p)):
    o = int(p[i])
    if o == 0 :
        labels1.append([0,1])
    else :
        labels1.append([1,0])

In [22]:
df['rnn'] = labels1

In [23]:
df.tail()

id                                               text  target     rnn
4395  16985  user user it takes sec google search to see wh...     0.0  [0, 1]
4396  44884  people are dead after shooting spree in califo...     0.0  [0, 1]
4397  84630  user user cupcakes suck it up she lost get ove...     0.0  [0, 1]
4398  67248                                user user yes he is     0.0  [0, 1]
4399  27429                                         user pussy     0.0  [0, 1]

In [24]:
df.head()

id                                               text  target     rnn
0  91976  user user user think it is safe bet that donal...     1.0  [1, 0]
1  15435                             user got your ass lmao     1.0  [1, 0]
2  63384  user dick durbin figures if he lies often enou...     1.0  [1, 0]
3  88928                                          user sexy     1.0  [1, 0]
4  21615  user user think he is racist out of touch with...     1.0  [1, 0]

In [25]:
df.target[3875]

1.0

In [26]:
df.target[3876]

0.0

In [27]:
df.rnn[3875]

[1, 0]

In [28]:
df.rnn[3876]

[0, 1]

In [29]:
df.text[785]

'user gutierrez you re such liar that all you guys are good for'

In [30]:
ids[785]

array([ 4832, 12466,    81,  1765,   125, 18939,    12,    64,    81,
        2284,    32,   219,    10,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0], dtype=int32)

In [31]:
from random import randint

def getTrainBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        if (i % 2 == 0): 
            num = randint(0,3200)
            labels.append(labels1[num])
        else:
            num = randint(4000,4398)
            labels.append(labels1[num])
        arr[i] = ids[num]
    return arr, labels

def getTestBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        num = randint(3200,4000)
        if (num <= 3876):
            labels.append(labels1[num])
        else:
            labels.append(labels1[num])
        arr[i] = ids[num]
    return arr, labels

In [32]:
batchSize = 24
pr,lr =  getTrainBatch()

In [33]:
len(pr)

24

In [34]:
batchSize = 24
lstmUnits = 64
numClasses = 2
iterations = 100000

In [35]:
import tensorflow as tf
tf.reset_default_graph()

labels = tf.placeholder(tf.float32, [batchSize, numClasses])
input_data = tf.placeholder(tf.int32, [batchSize, maxSeqLength])

In [36]:
data = tf.Variable(tf.zeros([batchSize, maxSeqLength, numDimensions]),dtype=tf.float32)
data = tf.nn.embedding_lookup(wordVectors,input_data)

In [37]:
lstmCell = tf.contrib.rnn.BasicLSTMCell(lstmUnits)
lstmCell = tf.contrib.rnn.DropoutWrapper(cell=lstmCell, output_keep_prob=0.75)
value, _ = tf.nn.dynamic_rnn(lstmCell, data, dtype=tf.float32)

Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').


In [38]:
weight = tf.Variable(tf.truncated_normal([lstmUnits, numClasses]))
bias = tf.Variable(tf.constant(0.1, shape=[numClasses]))
value = tf.transpose(value, [1, 0, 2])
last = tf.gather(value, int(value.get_shape()[0]) - 1)
prediction = (tf.matmul(last, weight) + bias)

In [39]:
correctPred = tf.equal(tf.argmax(prediction,1), tf.argmax(labels,1))
accuracy = tf.reduce_mean(tf.cast(correctPred, tf.float32))

In [40]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=labels))
optimizer = tf.train.AdamOptimizer().minimize(loss)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [41]:
import datetime

sess = tf.InteractiveSession()
tf.summary.scalar('Loss', loss)
tf.summary.scalar('Accuracy', accuracy)
merged = tf.summary.merge_all()
logdir = "tensorboard/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") + "/"
writer = tf.summary.FileWriter(logdir, sess.graph)

In [42]:
sess = tf.InteractiveSession()
saver = tf.train.Saver()
sess.run(tf.global_variables_initializer())

for i in range(iterations):
  nextBatch, nextBatchLabels = getTrainBatch();
  sess.run(optimizer, {input_data: nextBatch, labels: nextBatchLabels})
  if (i % 50 == 0):
    summary = sess.run(merged, {input_data: nextBatch, labels: nextBatchLabels})
    writer.add_summary(summary, i)
  if (i % 10000 == 0 and i != 0):
    save_path = saver.save(sess, "models/pretrained_lstm.ckpt", global_step=i)
    print("saved to %s" % save_path)
writer.close()

/home/preeti/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


saved to models/pretrained_lstm.ckpt-10000
saved to models/pretrained_lstm.ckpt-20000
saved to models/pretrained_lstm.ckpt-30000
saved to models/pretrained_lstm.ckpt-40000
saved to models/pretrained_lstm.ckpt-50000
saved to models/pretrained_lstm.ckpt-60000
saved to models/pretrained_lstm.ckpt-70000
saved to models/pretrained_lstm.ckpt-80000
saved to models/pretrained_lstm.ckpt-90000
