In [1]:
! ls

RNN_200_subb.ipynb	       wordList-200.npy
train_clean_subb_withuser.csv  wordVectors-200.npy


In [41]:
import numpy as np
import pandas as pd

csv = 'train_clean_subb_withuser.csv'
df = pd.read_csv(csv)
df.head()

id                                               text  target
0  86426  user she should ask few native americans what ...     0.0
1  90194                user user go home you re drunk user     1.0
2  62688  user someone should vetaken this piece of shit...     0.0
3  97670                       user liberals are all kookoo     1.0
4  77444                       user user oh noes tough shit     0.0

In [45]:
new_df = df.sort_values('target',ascending = False)

In [58]:
new_df.head()

id                                               text  target
1968  91976  user user user think it is safe bet that donal...     1.0
2634  15435                             user got your ass lmao     1.0
2606  63384  user dick durbin figures if he lies often enou...     1.0
2607  88928                                          user sexy     1.0
2608  21615  user user think he is racist out of touch with...     1.0

In [59]:
wordsList = np.load('wordList-200.npy')
print('Loaded the word list!')
wordsList = wordsList.tolist() #Originally loaded as numpy array
wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
wordVectors = np.load('wordVectors-200.npy')
print ('Loaded the word vectors!')

Loaded the word list!
Loaded the word vectors!


In [60]:
import tensorflow as tf
maxSeqLength = 10 #Maximum length of sentence
numDimensions = 100 #Dimensions for each word vector
firstSentence = np.zeros((maxSeqLength), dtype='int32')
firstSentence[0] = wordsList.index("i")
firstSentence[1] = wordsList.index("thought")
firstSentence[2] = wordsList.index("the")
firstSentence[3] = wordsList.index("movie")
firstSentence[4] = wordsList.index("was")
firstSentence[5] = wordsList.index("incredible")
firstSentence[6] = wordsList.index("and")
firstSentence[7] = wordsList.index("inspiring")
#firstSentence[8] and firstSentence[9] are going to be 0
print(firstSentence.shape)
print(firstSentence) #Shows the row index for each word

(10,)
[   41   804     0  1005    15  7446     5 13767     0     0]


In [61]:
#from os import listdir
#from os.path import isfile, join
#positiveFiles = ['positiveReviews/' + f for f in listdir('positiveReviews/') if isfile(join('positiveReviews/', f))]
#negativeFiles = ['negativeReviews/' + f for f in listdir('negativeReviews/') if isfile(join('negativeReviews/', f))]
numWords = []
k = new_df.text
k = np.array(k)

for i in range(len(k)) :
  line = str(k[i])
  counter = len(line.split())
  numWords.append(counter)
  
  

#for pf in positiveFiles:
#    with open(pf, "r", encoding='utf-8') as f:
#        line=f.readline()
#        counter = len(line.split())
#        numWords.append(counter)       
#print('Positive files finished')

#for nf in negativeFiles:
#    with open(nf, "r", encoding='utf-8') as f:
#        line=f.readline()
#        counter = len(line.split())
#        numWords.append(counter)  
#print('Negative files finished')

numFiles = len(numWords)
print('The total number of files is', numFiles)
print('The total number of words in the files is', sum(numWords))
print('The average number of words in the files is', sum(numWords)/len(numWords))



The total number of files is 4400
The total number of words in the files is 98451
The average number of words in the files is 22.375227272727273


In [75]:
k = new_df.text

In [76]:
maxSeqLength = 65

In [77]:
# Removes punctuation, parentheses, question marks, etc., and leaves only alphanumeric characters
import re
strip_special_chars = re.compile("[^A-Za-z0-9 ]+")

def cleanSentences(string):
    string = string.lower().replace("<br />", " ")
    return re.sub(strip_special_chars, "", string.lower())

In [78]:
ids = np.zeros((numFiles, maxSeqLength), dtype='int32')
fileCounter = 0

for i in range(len(k)) :
  indexCounter = 0
  line = str(k[i])
  cleanedLine = cleanSentences(line)
  split = cleanedLine.split()
  for word in split:
    try :
      ids[fileCounter][indexCounter] = wordsList.index(word)
    except ValueError:
      ids[fileCounter][indexCounter] = 399999
      
    indexCounter = indexCounter + 1  
    if indexCounter >= maxSeqLength:
      break
  fileCounter = fileCounter + 1   
      
      
      

# for pf in positiveFiles:
#    with open(pf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 

# for nf in negativeFiles:
#    with open(nf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 
# #Pass into embedding function and see if it evaluates. 

# np.save('idsMatrix', ids)

In [79]:
new_df.text[200]

'anyone surprised user'

In [81]:
k[200]

'anyone surprised user'

In [83]:
ids[200]

array([1544, 3553, 4832,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [84]:
np.save('idsMatrix_final', ids)

In [15]:
ids = np.load('idsMatrix.npy')

In [99]:
new_df.head()

id                                               text  target  \
1968  91976  user user user think it is safe bet that donal...     1.0   
2634  15435                             user got your ass lmao     1.0   
2606  63384  user dick durbin figures if he lies often enou...     1.0   
2607  88928                                          user sexy     1.0   
2608  21615  user user think he is racist out of touch with...     1.0   

         rnn    rnn1  
1968  [0, 1]  [0, 1]  
2634  [1, 0]  [1, 0]  
2606  [0, 1]  [0, 1]  
2607  [1, 0]  [1, 0]  
2608  [0, 1]  [0, 1]

In [97]:
labels1 = []
p = new_df.target
for i in range(len(p)):
    o = int(p[i])
    if o == 0 :
        labels1.append([0,1])
    else :
        labels1.append([1,0])

In [98]:
new_df['rnn1'] = labels1

In [85]:
labels1 = []
p = new_df.target
for i in range(len(p)):
  o = int(p[i])
  if o == 0.0 :
    labels1.append([0,1])
  else :
    labels1.append([1,0])

In [88]:
new_df['rnn'] = labels1

In [90]:
new_df.tail()

id                                               text  target     rnn
2803  16985  user user it takes sec google search to see wh...     0.0  [1, 0]
2808  44884  people are dead after shooting spree in califo...     0.0  [1, 0]
2815  84630  user user cupcakes suck it up she lost get ove...     0.0  [1, 0]
2819  67248                                user user yes he is     0.0  [1, 0]
4399  27429                                         user pussy     0.0  [0, 1]

In [19]:
df_1=pd.DataFrame(df[df.target == 1.0])
df_0=pd.DataFrame(df[df.target == 0.0])

In [20]:
frames = [df_1, df_0]

In [21]:
result = pd.concat(frames)


In [22]:

result = pd.concat(frames)


In [23]:
result.head()

id                                               text  target     rnn
1  90194                user user go home you re drunk user     1.0  [1, 0]
3  97670                       user liberals are all kookoo     1.0  [1, 0]
5  52415  user was literally just talking about this lol...     1.0  [1, 0]
6  13384  user canada doesn need another cuck we already...     1.0  [1, 0]
7  28414  user you are lying corrupt traitor nobody want...     1.0  [1, 0]

In [47]:
import numpy as np
k = np.array(new_df.text)
l = np.array(new_df.target)

In [25]:
len(df_1)

3876

In [26]:
len(df_0)

524

In [31]:
l[3875]

1.0

In [48]:
ids = np.zeros((numFiles, maxSeqLength), dtype='int32')
fileCounter = 0

for i in range(len(k)) :
  indexCounter = 0
  line = str(k[i])
  cleanedLine = cleanSentences(line)
  split = cleanedLine.split()
  for word in split:
    try :
      ids[fileCounter][indexCounter] = wordsList.index(word)
    except ValueError:
      ids[fileCounter][indexCounter] = 399999
      
    indexCounter = indexCounter + 1  
    if indexCounter >= maxSeqLength:
      break
  fileCounter = fileCounter + 1   
      
      
      

# for pf in positiveFiles:
#    with open(pf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 

# for nf in negativeFiles:
#    with open(nf, "r") as f:
#        indexCounter = 0
#        line=f.readline()
#        cleanedLine = cleanSentences(line)
#        split = cleanedLine.split()
#        for word in split:
#            try:
#                ids[fileCounter][indexCounter] = wordsList.index(word)
#            except ValueError:
#                ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#            indexCounter = indexCounter + 1
#            if indexCounter >= maxSeqLength:
#                break
#        fileCounter = fileCounter + 1 
# #Pass into embedding function and see if it evaluates. 

# np.save('idsMatrix', ids)

In [56]:
ids[200]

array([  4832,   4832,   4832,    120,    170,  41314,  40092,   6353,
         1883, 399999,  32281,  12681,   7696,   6296,    187,    934,
          120,    170,  78195,     25,      0,   3911,   2077,     37,
        33464,  71686,  15998,     18,   9644,    285,   3223,    135,
            6,      0,    699,      3,      0,    927,   5024,     71,
        10686,      6,     71,   4166,      5,  86232,   2827,    285,
         1797,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0], dtype=int32)

In [57]:
k[200]

'user user user just another blm brat blocking highway antifa thug swinging bike lock here comes just another screamer from the gallery except this childish scoundrel screamed he raped me sat down in the middle of the room stuck her thumb in her mouth and whined prove me wrong'