In [1]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
!ls

 agr_en_sm_test.csv
 Clean_Tweets_subb.ipynb
 clean_tweet_subb_only.csv
 data_vis.ipynb
 feature_normal_tfidf_algo_comp.ipynb
 offenseval-training-v1.tsv
'output_ml_Bernoulli NB.csv'
'output_ml_Multinomial NB.csv'
 output_ml_TFIDF.csv
 output_ml_with_output_file_generation_subb.ipynb
 term_freq_df.csv
 test_clean.csv
 test_tweet.csv


In [3]:
df = pd.read_csv("test_clean.csv", sep ='\t')

In [4]:
df.head()

sme_1  \
0  sme_2   
1  sme_3   
2  sme_4   
3  sme_5   
4  sme_6   

  6-0 hahahahahaha har ek pakistani ko yeh pic dikhao :) #indvspak #जयहिन्द http://t.co/xnrxlasipi  
0  @sardanarohit :While entire nation is praying ...                                                
1  shoaib: wahab riaz looks like johnson. kapil d...                                                
2  ramraj cottons r. ashwin southindian , chennai...                                                
3  #indvsuae jeet gaye... :) :) cmon starsports n...                                                
4  tt india 08:24 1.#indvspak 2.#mustwatchmsg 3.#...

In [5]:
df.rename({'sme_1':'id', '6-0 hahahahahaha har ek pakistani ko yeh pic dikhao :) #indvspak #जयहिन्द http://t.co/xnrxlasipi':'text'}, axis=1,inplace=True)

In [6]:
df.head()

id                                               text
0  sme_2  @sardanarohit :While entire nation is praying ...
1  sme_3  shoaib: wahab riaz looks like johnson. kapil d...
2  sme_4  ramraj cottons r. ashwin southindian , chennai...
3  sme_5  #indvsuae jeet gaye... :) :) cmon starsports n...
4  sme_6  tt india 08:24 1.#indvspak 2.#mustwatchmsg 3.#...

In [7]:
df['sentiment'] = -1.0
df.to_csv('agr_en_sm_test.csv')

In [8]:
df.head()

id                                               text  sentiment
0  sme_2  @sardanarohit :While entire nation is praying ...       -1.0
1  sme_3  shoaib: wahab riaz looks like johnson. kapil d...       -1.0
2  sme_4  ramraj cottons r. ashwin southindian , chennai...       -1.0
3  sme_5  #indvsuae jeet gaye... :) :) cmon starsports n...       -1.0
4  sme_6  tt india 08:24 1.#indvspak 2.#mustwatchmsg 3.#...       -1.0

In [9]:
df['pre_clean_len'] = [len(t) for t in df.text]

In [10]:
from nltk.tokenize import WordPunctTokenizer
tok = WordPunctTokenizer()

In [11]:
testing = df.text[:]

In [12]:
clean_df = pd.DataFrame()

clean_df['text'] = df.text
clean_df['target'] = df.sentiment
clean_df.head()


text  target
0  @sardanarohit :While entire nation is praying ...    -1.0
1  shoaib: wahab riaz looks like johnson. kapil d...    -1.0
2  ramraj cottons r. ashwin southindian , chennai...    -1.0
3  #indvsuae jeet gaye... :) :) cmon starsports n...    -1.0
4  tt india 08:24 1.#indvspak 2.#mustwatchmsg 3.#...    -1.0

In [13]:
clean_df.to_csv('test_tweet.csv',encoding='utf-8')

In [14]:
csv = 'clean_tweet_subb_only.csv'
my_df = pd.read_csv(csv,index_col=0)
my_df.head()

text  target
0  @USER She should ask a few native Americans wh...     0.0
1  @USER @USER Go home you’re drunk!!! @USER #MAG...     1.0
3  @USER Someone should'veTaken" this piece of sh...     0.0
5                  @USER Liberals are all Kookoo !!!     1.0
6                   @USER @USER Oh noes! Tough shit.     0.0

In [15]:
my_df.dropna(inplace=True)
my_df.reset_index(drop=True,inplace=True)
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4400 entries, 0 to 4399
Data columns (total 2 columns):
text      4400 non-null object
target    4400 non-null float64
dtypes: float64(1), object(1)
memory usage: 68.8+ KB


In [16]:
x = my_df.text
y = my_df.target

In [17]:
from sklearn.model_selection import train_test_split
SEED = 50
x_train, x_validation_and_test, y_train, y_validation_and_test = train_test_split(x, y, test_size=.001, random_state=SEED)
x_validation, x_test, y_validation, y_test = train_test_split(x_validation_and_test, y_validation_and_test, test_size=.000001, random_state=SEED)

In [18]:
print ("Train set has total {0} entries with {1:.2f}% negative, {2:.2f}% positive".format(len(x_train),
                                                                             (len(x_train[y_train == 0]) / (len(x_train)*1.))*100,
                                                                            (len(x_train[y_train == 1]) / (len(x_train)*1.))*100))
print ("Validation set has total {0} entries with {1:.2f}% negative, {2:.2f}% positive".format(len(x_validation),
                                                                             (len(x_validation[y_validation == 0]) / (len(x_validation)*1.))*100,
                                                                            (len(x_validation[y_validation == 1]) / (len(x_validation)*1.))*100))
print ("Test set has total {0} entries with {1:.2f}% negative, {2:.2f}% positive".format(len(x_test),
                                                                             (len(x_test[y_test == 0]) / (len(x_test)*1.))*100,
                                                                            (len(x_test[y_test == 1]) / (len(x_test)*1.))*100))



Train set has total 4395 entries with 11.92% negative, 88.08% positive
Validation set has total 4 entries with 0.00% negative, 100.00% positive
Test set has total 1 entries with 0.00% negative, 100.00% positive


In [19]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1256 entries, 0 to 1255
Data columns (total 2 columns):
text      1256 non-null object
target    1256 non-null float64
dtypes: float64(1), object(1)
memory usage: 19.7+ KB


In [20]:
x_test=clean_df.text
y_test=clean_df.target

In [21]:
"""PROCEDURE FOR TFIDF N_GRAMS, PLEASE RUN ONLY ONCE"""

'PROCEDURE FOR TFIDF N_GRAMS, PLEASE RUN ONLY ONCE'

In [22]:
# Baseline

In [23]:
from textblob import TextBlob
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix


In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from time import time

In [25]:
def accuracy_summary(pipeline, x_train, y_train, x_test, y_test):
    if len(x_test[y_test == 0]) / (len(x_test)*1.) > 0.5:
        null_accuracy = len(x_test[y_test == 0]) / (len(x_test)*1.)
    else:
        null_accuracy = 1. - (len(x_test[y_test == 0]) / (len(x_test)*1.))
    t0 = time()
    sentiment_fit = pipeline.fit(x_train, y_train)
    y_pred = sentiment_fit.predict(x_test)
    train_test_time = time() - t0
    y_test=y_pred
    accuracy = y_pred
    return accuracy, train_test_time

In [26]:
cvec = CountVectorizer()
lr = LogisticRegression()
n_features = np.arange(10000,100001,10000)

def nfeature_accuracy_checker(vectorizer=cvec, n_features=n_features, stop_words=None, ngram_range=(1, 1), classifier=lr):
    result = []
    print (classifier)
    print ("\n")
    for n in n_features:
        vectorizer.set_params(stop_words=stop_words, max_features=n, ngram_range=ngram_range)
        checker_pipeline = Pipeline([
            ('vectorizer', vectorizer),
            ('classifier', classifier)
        ])
        nfeature_accuracy,tt_time = accuracy_summary(checker_pipeline, x_train, y_train, x_validation, y_validation)
        result.append((n,nfeature_accuracy,tt_time))
    return nfeature_accuracy

In [27]:
def train_test_and_evaluate(pipeline, x_train, y_train, x_test, y_test):
    if len(x_test[y_test == 0]) / (len(x_test)*1.) > 0.5:
        null_accuracy = len(x_test[y_test == 0]) / (len(x_test)*1.)
    else:
        null_accuracy = 1. - (len(x_test[y_test == 0]) / (len(x_test)*1.))
    sentiment_fit = pipeline.fit(x_train, y_train)
    y_pred = sentiment_fit.predict(x_test)
    y_test=y_pred
    return y_test
    """conmat = np.array(confusion_matrix(y_test, y_pred, labels=[0,1]))
    confusion = pd.DataFrame(conmat, index=['negative', 'positive'],
                         columns=['predicted_negative','predicted_positive'])
   print ("null accuracy: {0:.2f}%".format(null_accuracy*100))
    print ("accuracy score: {0:.2f}%".format(accuracy*100))
    if accuracy > null_accuracy:
        print ("model is {0:.2f}% more accurate than null accuracy".format((accuracy-null_accuracy)*100))
    elif accuracy == null_accuracy:
        print ("model has the same accuracy with the null accuracy")
    else:
        print ("model is {0:.2f}% less accurate than null accuracy".format((null_accuracy-accuracy)*100))
    print ("-"*80)
    print ("Confusion Matrix\n")
    print (confusion)
    print ("-"*80)
    print ("Classification Report\n")
    print (classification_report(y_test, y_pred, target_names=['negative','positive']))"""


In [28]:
%%time
ug_cvec = CountVectorizer(max_features=100000)
ug_pipeline = Pipeline([
        ('vectorizer', ug_cvec),
        ('classifier', lr)
    ])
y_test=train_test_and_evaluate(ug_pipeline, x_train, y_train, x_test, y_test)

CPU times: user 378 ms, sys: 11.9 ms, total: 390 ms
Wall time: 231 ms


In [29]:
y_test

array([ 1.,  1.,  1., ...,  1.,  0.,  1.])

In [30]:
len(y_test)

1256

In [31]:
len(x_test)

1256

In [32]:
clean2_df = pd.DataFrame({'id':df.id, 'sentiment':y_test})
clean2_df.head()

id  sentiment
0  sme_2        1.0
1  sme_3        1.0
2  sme_4        1.0
3  sme_5        1.0
4  sme_6        1.0

In [33]:
clean2_df.to_csv('output_ml_TFIDF.csv',encoding='utf-8')

In [34]:
"""FOR OTHER SPECIFIC ALGORITHMS"""

'FOR OTHER SPECIFIC ALGORITHMS'

In [35]:
x_test=clean_df.text
y_test=clean_df.target

In [36]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import Perceptron
from sklearn.neighbors import NearestCentroid
from sklearn.feature_selection import SelectFromModel

names = ["Logistic Regression", "Linear SVC", "LinearSVC with L1-based feature selection","Multinomial NB", 
         "Bernoulli NB", "Ridge Classifier", "AdaBoost", "Perceptron","Passive-Aggresive", "Nearest Centroid"]
classifiers = [
    LogisticRegression(),
    LinearSVC(),
    Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1", dual=False))),
  ('classification', LinearSVC(penalty="l2"))]),
    MultinomialNB(),
    BernoulliNB(),
    RidgeClassifier(),
    AdaBoostClassifier(),
    Perceptron(),
    PassiveAggressiveClassifier(),
    NearestCentroid()
    ]
zipped_clf = zip(names,classifiers)

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer()

def classifier_comparator(vectorizer=tvec, n_features=10000, stop_words=None, ngram_range=(1, 1), classifier=zipped_clf):
    result = []
    vectorizer.set_params(stop_words=stop_words, max_features=n_features, ngram_range=ngram_range)
    for n,c in classifier:
        checker_pipeline = Pipeline([
            ('vectorizer', vectorizer),
            ('classifier', c)
        ])
        print ("Validation result for {}".format(n))
        print (c)
        clf_accuracy,tt_time = accuracy_summary(checker_pipeline, x_train, y_train, x_validation, y_validation)
        result.append((n,clf_accuracy,tt_time))
    return result

In [38]:
"""Output for individulal classifier mention it in the last cell refer to the second last cell for legend. We have got max earlier for Bernoulli NB So I am  doing the same below using bigrams"""

'Output for individulal classifier mention it in the last cell refer to the second last cell for legend. We have got max earlier for Bernoulli NB So I am  doing the same below using bigrams'

In [39]:
names = ["Bernoulli NB"]
classifiers = [BernoulliNB()]
zipped_clf = zip(names,classifiers)

In [40]:
cvec = CountVectorizer()
def classifier_comparator(vectorizer=cvec, n_features=10000, stop_words=None, ngram_range=(1, 1), classifier=zipped_clf):
    result = []
    vectorizer.set_params(stop_words=stop_words, max_features=n_features, ngram_range=ngram_range)
    for n,c in classifier:
        checker_pipeline = Pipeline([
            ('vectorizer', vectorizer),
            ('classifier', c)
        ])
        print (c)
        clf_accuracy,tt_time = accuracy_summary(checker_pipeline, x_train, y_train, x_test, y_test)
    return clf_accuracy

In [41]:
%%time
y_test = classifier_comparator(n_features=20000,ngram_range=(1,2))

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)
CPU times: user 534 ms, sys: 11.9 ms, total: 546 ms
Wall time: 458 ms


In [42]:
y_test

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [43]:
len(y_test)

1256

In [44]:
clean2_df = pd.DataFrame({'id':df.id, 'sentiment':y_test})
clean2_df.head()

id  sentiment
0  sme_2        1.0
1  sme_3        1.0
2  sme_4        1.0
3  sme_5        1.0
4  sme_6        1.0

In [45]:
clean2_df.to_csv('output_ml_Bernoulli NB.csv',encoding='utf-8')

In [46]:
"""YET OTHER ALGOS WITHOUT BIAGRAMS- Multinomial NB"""

'YET OTHER ALGOS WITHOUT BIAGRAMS- Multinomial NB'

In [47]:
x_test=clean_df.text
y_test=clean_df.target

In [48]:
from sklearn.ensemble import VotingClassifier

clf1 = LogisticRegression()
clf2 = LinearSVC()
clf3 = MultinomialNB()
clf4 = RidgeClassifier()
clf5 = PassiveAggressiveClassifier()
clf6 = AdaBoostClassifier()

eclf = VotingClassifier(estimators=[('lr', clf1), ('svc', clf2), ('mnb', clf3), ('rcs', clf4), ('pac', clf5), ('ada', clf5)], voting='hard')

for clf, label in zip([ clf3,eclf], ['Multinomial NB']):
    checker_pipeline = Pipeline([
            ('vectorizer', TfidfVectorizer(max_features=20000,ngram_range=(1, 2))),
            ('classifier', clf)
        ])
    print ("Validation result for {}".format(label))
    print (clf)
    y_test,tt_time = accuracy_summary(checker_pipeline, x_train, y_train, x_test, y_test)

Validation result for Multinomial NB
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [49]:
y_test

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [50]:
len(y_test)

1256

In [51]:
clean2_df = pd.DataFrame({'id':df.id, 'sentiment':y_test})
clean2_df.head()

id  sentiment
0  sme_2        1.0
1  sme_3        1.0
2  sme_4        1.0
3  sme_5        1.0
4  sme_6        1.0

In [52]:
clean2_df.to_csv('output_ml_Multinomial NB.csv',encoding='utf-8')